### ISSUE TITLE
InternalSubnets

### ISSUE THREAD

**Issue by secf00tprint** [activecm/rita#526]
I installed RITA on Ubuntu 18.04 using `sudo ./install.sh`
Now when I want to import Zeek Logs I get: 
```
rita import zeeklogs_path db

Internal subnets are not defined. Please set the InternalSubnets section of the config file.
```

Rita-Version: `v3.1.1`

I changed `etc/rita.yaml` to include none, one or all IP-Ranges in `Filtering:InternalSubnets`

What I'm doing wrong?

**Comment by lisaSW** [comment]
Would you mind showing exactly what the Internal Subnets section of your /etc/rita/config.yaml looks like? 

![image](https://user-images.githubusercontent.com/6879542/71904230-fe1a3180-3122-11ea-9c35-91690d736c33.png)

**Comment by secf00tprint** [comment]
Looks exactly like that

**Comment by ethack** [comment]
@secf00tprint Can you confirm the full path to the config file? The one that rita looks for is `/etc/rita/config.yaml` and not `etc/rita.yaml`. It's named `etc/rita.yaml` in the source code repo but that's copied to `/etc/rita/config.yaml` during the install.

Another thing you can try is running `rita test-config` to see what config is actually being loaded. This helps spot errors in the config formatting as well. If you're internal subnets aren't defined it will look like this:
``` 
Filtering:
  AlwaysInclude: []
  NeverInclude:
  - 0.0.0.0/32
  - 127.0.0.0/8
  - 169.254.0.0/16
  - 224.0.0.0/4
  - 255.255.255.255/32
  - ::1/128
  - fe80::/10
  - ff00::/8
  InternalSubnets: []
```

If they are it will look like this:
```
Filtering:
  AlwaysInclude: []
  NeverInclude:
  - 0.0.0.0/32
  - 127.0.0.0/8
  - 169.254.0.0/16
  - 224.0.0.0/4
  - 255.255.255.255/32
  - ::1/128
  - fe80::/10
  - ff00::/8
  InternalSubnets:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
```
