### ISSUE TITLE
Error while running the Docker container

### ISSUE THREAD

**Issue by a-ml** [activecm/rita#828]
Hello,

I'm using the docker container using the docker compose.

Here the configuration file:

```
version: '3'

services:
  db:
    image: mongo:4.2
    volumes:
      - db:/data/db/

  rita:
    image: quay.io/activecm/rita:${VERSION:-latest}
    build: .
    depends_on:
      - db
    volumes:
      - /opt/rita/config/rita_docker.yaml:/etc/rita/config.yaml:ro
      - /opt/zeek/logs/:/logs:ro

volumes:
  db:
```

Here the error:

```
vps@vps01:/opt/rita$ sudo docker compose up
WARN[0000] /opt/rita/docker-compose.yml: `version` is obsolete
[+] Running 3/0
 ✔ Container rita-db-1                                                                                                                                 Running                                                                          0.0s
 ✔ Container rita-rita-1                                                                                                                               Created                                                                          0.0s
 ! rita The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                                                                  0.0s
Attaching to db-1, rita-1
rita-1  | exec /rita: exec format error
rita-1 exited with code 1
```

Can anyone help me understand which error is this? I'm using without detach but not receiving any useful information.
